language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: "Tests without proxy"
      name: "Tests without proxy"
      script: npm run test
    - stage: "Tests with proxy"
      name: "Tests with proxy"
      script: npm run test-proxy

cache:
  npm: true
  directories:
    - node_modules

