language: node_js
node_js:
  - 12

#before_install:
#  - npm install -g anyproxy && nohup anyproxy --port 8001 & &&

jobs:
  include:
    - stage: "Tests [no proxy]"
      name: "Unit Tests"
      script: npm run test
    - stage: "Tests [proxy]"
      name: "Unit Tests with proxy"
      script: npm install -g anyproxy
    - script: nohup anyproxy --port 8001 &
    - script: npm run test-proxy

cache:
  directories:
    - node_modules

