language: node_js
node_js:
  - 12

before_install:
  - npm install -g anyproxy
  - nohup anyproxy --port 8001 &

jobs:
  include:
    - stage: "Tests [no proxy]"
      name: "Unit Tests"
      script: 'npm run test && printf "\nhttpProxy: http://localhost:8001\n" >> tests/config.test.yml'
    - stage: "Tests [with proxy]"
      name: "Unit Tests"
      script: npm run test

cache:
  directories:
    - node_modules

