language: node_js
node_js:
  - 12

before_install:
  - npm install -g anyproxy
  - nohup anyproxy --port 8001 &
  - 'printf "\nhttpProxy: http://localhost:8001\n" >> tests/config.test.yml'

cache:
  directories:
    - node_modules

